# Environment configuration
env: "dev" # Options: dev, staging, production

# Logging configuration
log_level: "info"

# Server configuration
server:
  host: "0.0.0.0"
  port: 8443
  cert: "cert.pem"
  key: "key.pem"
  mode: "release"
  read_timeout: "15s"
  write_timeout: "15s"
  trusted_proxies: []

# CORS configuration
cors:
  allow_origins:
    - "*"
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Origin"
    - "Content-Length"
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"
  expose_headers:
    - "Content-Length"
  allow_credentials: false
  max_age: "12h"

# Error reporting with Bugsnag (optional)
bugsnag:
  api_key: "" # Bugsnag API key (leave empty to disable)
  release_stage: "dev" # Release stage for error reporting
  log_level: "info" # Minimum log level for Bugsnag reporting
